services:
  frontend:
    image: 331005568745.dkr.ecr.us-east-1.amazonaws.com/delivery-tracking:frontend-TAG
    container_name: tracking-hub-frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /home/ec2-user/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /home/ec2-user/privkey.pem:/etc/ssl/private/privkey.pem:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
